apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
    useBuildkit: true
  artifacts:
    - image: kodrclub/kodrops-client-dev
      context: client
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: './**/*.js'
            dest: .

    - image: kodrclub/kodrops-backend
      context: backend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: './**/*.js'
            dest: .

    - image: kodrclub/kodrops-hello
      context: hello
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: './**/*.js'
            dest: .
