apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: kodrclub/bcdop-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: './**/*.js'
            dest: .

    - image: kodrclub/bcdop-server
      context: server
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: './**/*.js'
            dest: .

    - image: kodrclub/bcdop-hello
      context: hello
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: './**/*.js'
            dest: .
