apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    ##############
    # cert-manager.io/issuer: 'letsencrypt-staging'
    cert-manager.io/issuer: 'letsencrypt-prod'
    ##############

spec:
  ##############
  tls:
    - hosts:
        - kodr.xyz ##################
      secretName: kodr-tls
  ##############

  rules:
    - host: kodr.xyz ##################
      http:
        paths:
          - path: /api/?(.*)
            backend:
              serviceName: backend-srv
              servicePort: 3000

          - path: /hello/?(.*)
            backend:
              serviceName: hello-srv
              servicePort: 3000

          - path: /?(.*)
            backend:
              serviceName: client-srv
              servicePort: 80
