{
 "title": "kodrops requests",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "ds_prometheus", "query": "Prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Successful request count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tlk_http_requests_total{route=\"/api/movie\",method=\"POST\",status=\"2XX\"} ",
     "legendFormat": "Create"
    },
    {
     "expr": "tlk_http_requests_total{route=\"/api/movies\",method=\"GET\",status=\"2XX\"} ",
     "legendFormat": "List"
    }
   ]
  },
  {
   "title": "Unsuccessful creation count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tlk_http_requests_total{route=\"/api/movie\",method=\"POST\",status!=\"2XX\"} ",
     "legendFormat": "Create"
    }
   ]
  },
  {
   "title": "Successful request  rate (5m)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(tlk_http_requests_total{route=\"/api/movie\",method=\"POST\",status=\"2XX\"}[5m])",
     "legendFormat": " Create"
    },
    {
     "expr": "rate(tlk_http_requests_total{route=\"/api/movies\",method=\"GET\",status=\"2XX\"}[5m])",
     "legendFormat": " List"
    }
   ]
  },
  {
   "title": "Unsuccessful creation rate (1h)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(tlk_http_requests_total{route=\"/api/movie\",method=\"POST\",status!=\"2XX\"}[1h])",
     "legendFormat": " Create"
    }
   ]
  }
 ]
}