name: deploy-backend

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: docker build -t kodrclub/kodrops-backend backend
        env:
          DOCKER_BUILDKIT: 1
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push kodrclub/kodrops-backend

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud container clusters get-credentials $GCP_CLUSTER_NAME --$GCP_LOCATION_TYPE $GCP_LOCATION
        env:
          GCP_CLUSTER_NAME: ${{ secrets.GCP_CLUSTER_NAME }}
          GCP_LOCATION: ${{ secrets.GCP_LOCATION }}

      - run: kubectl rollout restart deployment backend-depl -n kodrops
