name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/k8s/**'
      - 'infra/k8s-prod/**'
      - 'infra/k8s-prod-monit/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Get cluster credentials
        run: gcloud container clusters get-credentials $GCP_CLUSTER_NAME --$GCP_LOCATION_TYPE $GCP_LOCATION
        env:
          GCP_CLUSTER_NAME: ${{ secrets.GCP_CLUSTER_NAME }}
          GCP_LOCATION_TYPE: ${{ secrets.GCP_LOCATION_TYPE }}
          GCP_LOCATION: ${{ secrets.GCP_LOCATION }}

      - name: Install kubeval
        run: |
          wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          sudo cp kubeval /usr/local/bin

      - name: Test manifests
        run: make test-prod-manifests

      - name: Deploy manifests
        run: make deploy-prod-manifests
