name: deploy-manifests

on:
  push:
    branches:
      - deploy
    paths:
      - 'infra/k8s/**'
      - 'infra/k8s-prod/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud container clusters get-credentials $GCP_CLUSTER_NAME --zone $GCP_ZONE
        env:
          GCP_CLUSTER_NAME: ${{ secrets.GCP_CLUSTER_NAME }}
          GCP_ZONE: ${{ secrets.GCP_ZONE }}

      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
