name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Please confirm that you want to DESTROY the infrastructure by typing 'yes' (with no quotation marks) below"
        required: true
        default: 'no'
      home:
        description: 'location'
        required: false

jobs:
  terraform_destroy:
    name: 'Terraform DESTROY'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GCP for Terraform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY_TERRAFORM }}
          export_default_credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform DESTROY
        run: "$( [[ ${{ github.events.inputs.confirmation }} = 'yes' ]] && echo 'DESTROY' || echo 'Destruction not confirmed.' )"

        # run: cd infra/gcp && terraform apply -auto-approve "planfile"
