name: tests-client

on:
  pull_request:
    paths:
      - 'client/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && npm install && npm run test:ci
